version: '3'

services:
  gui:
    environment:
      DEBUG_CLIENT_IP: 'host.docker.internal'
    container_name: gui
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8081:80'
    expose:
      - '8081'
