<?php
/**
 * @var int $movieId
 */

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Details</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <style>
        /* Custom Styles */
        body {
            background-color: #222;
        }

        .main-container {
            padding: 20px;
        }


        .movie-details,
        .recommended-details {
            position: relative;
            max-width: 960px;
            margin: 0 auto;
            background-color: #333;
            color: #f5f5f5;
            padding: 20px;
            box-shadow: 0px 0px 30px rgba(0, 0, 0, 0.1);
            overflow: hidden; /* Add this */
            /* Other styles... */
        }


        /* Image max-width rule */
        .movie-details img,
        .recommended-details .swiper-slide img {
            max-width: 100%;
        }

        .navbar {
            background-color: #1b1b1b;
        }

        .navbar-brand {
            color: #c81010;
        }

        .swiper-container {
            width: 100%;
            height: 400px;
        }

        .swiper-button-next,
        .swiper-button-prev {
            position: absolute;
            top: 50%;
            transform: translateY(-50%);
            width: 30px;
            height: 30px;
            background-color: #c81010;
            color: #f5f5f5;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            z-index: 1;
        }

        .swiper-button-next {
            right: 0;
        }

        .swiper-button-prev {
            left: 0;
        }

        .swiper-slide {
            text-align: center;
        }

        .swiper-slide img {
            display: block;
            margin: 0 auto;
            max-height: 300px;
        }

        .swiper-slide h5 {
            margin-top: 10px;
            font-size: 18px;
            color: #c81010;
        }

        .no-image-holder {
            font-size: 100px;
            color: #bbb;
            text-align: center;
        }

        h1, h2 {
            color: #c81010;
        }

        p {
            color: #f5f5f5;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="https://www.etv.co.za/themes/custom/fd_etv2019/logo.svg" width="30" height="30" alt="Logo">
            Home
        </a>
    </div>
</nav>

<div class="main-container">



    <div id="movie-details-loader" style="display: none; text-align: center;">
        <img src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/0.16.1/images/loader-large.gif" alt="loading..." />
        <p>Loading Movie Details...</p>
    </div>
    <div class="alert alert-danger" id="details-error-message" style="display: none;"></div>
    <div class="movie-details" style="display: none;">
        <h1>Movie Details</h1>
        <div class="row">
            <div class="col-md-4">
                <img id="movie-poster" src="" class="img-fluid" alt="Movie Poster">
            </div>
            <div class="col-md-8">
                <h2 id="movie-title"></h2>
                <p id="movie-overview"></p>
                <p><strong>Release Date:</strong> <span id="movie-release-date"></span></p>
                <p><strong>Runtime:</strong> <span id="movie-runtime"></span> minutes</p>
                <p><strong>Revenue:</strong> $<span id="movie-revenue"></span></p>
                <p><strong>Vote Average:</strong> <span id="movie-vote-average"></span></p>
            </div>
            <div class="no-image-holder">
                <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
            </div>
        </div>
    </div>


    <div id="recommended-movies-loader" style="display: none; text-align: center;">
        <img src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/0.16.1/images/loader-large.gif" alt="loading..." />
        <p>Loading Recommended Movies...</p>
    </div>
    <div class="alert alert-danger" id="recommended-error-message" style="display: none;"></div>
    <div class="recommended-details" style="display: none;">
        <h2>Recommended Movies</h2>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <!-- Slides will be populated by AJAX call -->
            </div>
            <!-- Moving buttons inside the ".recommended-details" div -->
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </div>
    </div>



</div>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>

    var movieId = <?php echo $movieId ?>;

    var imagePath = 'https://image.tmdb.org/t/p/w500/';


    movieDetails(movieId);

    recommendedMovies(movieId);


    function movieDetails(movieId)
    {
        $('#movie-details-loader').show();
        $.ajax({
            url: 'http://localhost:8080/api/detail/'+movieId,
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                // Populate the movie details
                if(data.poster_path) {
                    $('#movie-poster').attr('src', imagePath + data.poster_path);
                } else {
                    $('#movie-poster').attr('src', 'https://placehold.co/500x750?text=Image+Not+Found');
                }

                $('#movie-title').text(data.title);
                $('#movie-overview').text(data.overview);
                $('#movie-release-date').text(data.release_date);
                $('#movie-runtime').text(data.runtime);
                $('#movie-revenue').text(data.revenue);
                $('#movie-vote-average').text(data.vote_average);

                // Hide loader and show content
                $('#movie-details-loader').hide();
                $('.movie-details').show();

            },
            error: function(error) {
                console.log('Error:', error);

                $('#movie-details-loader').hide();
                $('.movie-details').hide();
                $('#details-error-message').text('We could not obtain the recommended titles').show();
            }
        });
    }


    function recommendedMovies(movieId)
    {

        $('#recommended-movies-loader').show();
        $.ajax({
            url: 'http://localhost:8080/api/recommended/'+movieId,
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                // Check if data exists and has at least one movie
                if(data && data.length > 0) {
                    // Loop through the recommended movies
                    $.each(data, function(index, movie) {
                        var slide = $('<div>').addClass('swiper-slide').attr('data-movie-id', movie.id).on('click', function() {
                            var movieId = $(this).attr('data-movie-id');
                            var url = 'http://localhost:8081/movie/view/' + movieId;
                            window.open(url, '_blank');
                        });
                        var title = $('<h5>').text(movie.title);
                        var img;

                        // Check if there is a poster for the movie
                        if(movie.poster_path) {
                            img = $('<img>').attr('src', imagePath + movie.poster_path);
                        } else {
                            img = $('<img>').attr('src', 'https://placehold.co/500x750?text=Image+Not+Found');
                        }

                        // Add the title and image to the slide div
                        slide.append(img).append(title);

                        // Add the slide to the swiper-wrapper div
                        $('.swiper-wrapper').append(slide);
                    });

                    // Re-initialize Swiper
                    swiper = new Swiper('.swiper-container', {
                        slidesPerView: 3,
                        spaceBetween: 20,
                        navigation: {
                            nextEl: '.swiper-button-next',
                            prevEl: '.swiper-button-prev',
                        },
                        loop: true,
                        autoplay: {
                            delay: 3000,
                        },
                    });

                    // Show the recommended movies section
                    $('#recommended-movies-loader').hide();
                    $('.recommended-details').show();
                }
                else
                {
                    // Show message and hide loader
                    $('#recommended-movies-loader').hide();
                    $('#recommended-error-message').text('There are no recommended titles for this one...').show();
                }
            },
            error: function(error) {
                console.log('Error:', error);
                $('#recommended-movies-loader').hide();
                $('.recommended-details').hide();
            }
        });
    }
</script>

</body>
</html>
